ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS retries_used INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_retries INTEGER NOT NULL DEFAULT 0;

ALTER TABLE task_results
    ADD COLUMN IF NOT EXISTS summary TEXT;
